# Generated by Django 4.1.7 on 2023-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact",
            },
        ),
    ]
