# Generated by Django 4.1.7 on 2023-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=50)),
                ("birthday", models.DateField()),
                ("email", models.EmailField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("c_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "associator",
            },
        ),
    ]
