"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os   #新增

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9@_1o6lvrv%y+q&v)zvstqny$3%pif22tcj---7g_q8zr=bl=1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "news",     #最新消息
    "product",  #產品頁
    "contact",  #聯絡我們
    "member",   #會員資料
    "cart",     #購物車
    "photos",   #檔案上傳區
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myweb.urls"

TEMPLATES = [   #放HTML檔案
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates').replace('\\','/')], #取代成網頁用的反斜線
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myweb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

import pymysql  #串接MySQL
# pymysql.version_info(1,0,10,'final',0) #若有版本問題可使用指定版本來更新
pymysql.install_as_MySQLdb()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": 'yongheSoyMilk',    #資料庫名稱
        'USER': 'yhgood',           #由一個非最高權限的帳號去登入(非root)
        'PASSWORD': '987654321',
        'HOST': 'Localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-Hant"  # 設定後臺介面為繁體中文

TIME_ZONE = "Asia/Taipei"  #亞洲台北時區

USE_I18N = True # 是否要把語言做國際化(預設True就好)

USE_TZ = False  # 不使用當地時間，而使用TIME_ZONE 時區


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 靜態路徑
STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR,'static')   #根目錄

STATICFILES_DIRS = (
    ('images',os.path.join(STATIC_ROOT,'images').replace('\\','/')),
    ('css',os.path.join(STATIC_ROOT,'css').replace('\\','/')),
    ('js',os.path.join(STATIC_ROOT,'js').replace('\\','/')),
    )

#設定多媒體資料夾
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#將session 在瀏覽器關閉時自動結束(預設是False，不會結束)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#設定session的有效時間
SESSION_COOKIE_AGE = 1200 #60秒 * 20分 = 1200秒(沒寫的話預設保留2週)
